In [0]:
import pandas as pd
import numpy as np

In [0]:
# # table is Unity Catalog, so need to open like this
# south_sudan_funding_requirements = spark.table('workspace.default.requirements_funding_cluster_south_sudan')
# display(south_sudan_funding_requirements.limit(5))

In [0]:
funding_requirements_global_cluster = pd.read_csv('/Workspace/Users/maic@ufl.edu/fts_requirements_funding_global_cluster_2025.csv')

funding_requirements_global_cluster = funding_requirements_global_cluster.dropna(axis=0)
funding_requirements_global_cluster

    countryCode    id  ...      funding percentFunded
1           AFG  1263  ...    7101118.0          21.0
3           AFG  1263  ...   80113551.0          86.0
4           AFG  1263  ...   28287010.0          16.0
5           AFG  1263  ...  202583088.0          19.0
6           AFG  1263  ...  127002611.0          45.0
..          ...   ...  ...          ...           ...
611         ZWE  1280  ...    1545466.0          23.0
612         ZWE  1280  ...     477106.0         173.0
614         ZWE  1280  ...    1224531.0          12.0
616         ZWE  1280  ...      37778.0           4.0
618         ZWE  1280  ...     287425.0           2.0

[434 rows x 12 columns]

In [0]:
needs = pd.read_csv('/Workspace/Users/maic@ufl.edu/hpc_hno_2025.csv')
# remove nulls and empty strings from Cluster column
clean_clusters = needs['Cluster'].dropna()
clean_clusters = clean_clusters[clean_clusters.str.strip() != '']
clean_clusters

/home/spark-ac93f664-2b42-4d1c-9921-e0/.ipykernel/2607/command-8059258230355133-1179970297:1: DtypeWarning: Columns (1,2,5,6,15) have mixed types. Specify dtype option on import or set low_memory=False.
  needs = pd.read_csv('/Workspace/Users/maic@ufl.edu/hpc_hno_2025.csv')

0         ALL
1         ALL
2         ALL
3         ALL
4         ALL
         ...
318254    WSH
318255    WSH
318256    WSH
318257    WSH
318258    WSH
Name: Cluster, Length: 312689, dtype: object

In [0]:
needs['Cluster'].unique()

# full names for cluster codes (from Financial Tracking Services)
clusters = {
    'ALL':'All Sectors',
    'CSS': 'Coordination and Support Services',
    'EDU': 'Education',
    'FSC': 'Food Security',
    'HEA': 'Health',
    'LOG': 'Logistics',
    'MPC': 'Multipurpose Cash',
    'NUT': 'Nutrition',
    'PRO': 'Protection',
    'PRO-CPN': 'Protection - Child Protection',
    'PRO-GBV': 'Protection - Gender-Based Violence',
    'PRO-HLP': 'Protection - Housing, Land and Property',
    'PRO-MIN': 'Protection - Mine Action',
    'SHL': 'Emergency Shelter and NFI',
    'WSH': 'Water Sanitation Hygiene',
    'CCM': 'Camp Coordination and Camp Management',
    'MS': 'Multi-sector',
    'ERY': 'Early Recovery',
    'TEL': 'Emergency Telecommunications'
}

# add column with full cluster names based on codes
needs['Cluster Full'] = needs['Cluster'].map(clusters)
needs.head()

  Country ISO3 Admin 1 PCode Admin 1 Name  ...     Reached Info Cluster Full
0          AFG           NaN          NaN  ...  18100000.0  NaN  All Sectors
1          AFG           NaN          NaN  ...         NaN  NaN  All Sectors
2          AFG           NaN          NaN  ...         NaN  NaN  All Sectors
3          AFG           NaN          NaN  ...         NaN  NaN  All Sectors
4          AFG           NaN          NaN  ...         NaN  NaN  All Sectors

[5 rows x 17 columns]

In [0]:
funding_requirements_global_cluster.to_csv('funding_requirements_global_clusters.csv')

In [0]:
total_needs = needs[needs['Category'] == 'total']
total_needs_for_all_cluster = total[total['Cluster'] == 'ALL']
total_needs_for_all_cluster

       Country ISO3 Admin 1 PCode Admin 1 Name  ... Reached Info Cluster Full
46              AFG           NaN          NaN  ...     NaN  NaN  All Sectors
513             AFG          AF01        Kabul  ...     NaN  NaN  All Sectors
960             AFG           NaN          NaN  ...     NaN  NaN  All Sectors
1387            AFG           NaN          NaN  ...     NaN  NaN  All Sectors
1632            AFG           NaN          NaN  ...     NaN  NaN  All Sectors
...             ...           ...          ...  ...     ...  ...          ...
317953          YEM           NaN          NaN  ...     NaN  NaN  All Sectors
318017          YEM           NaN          NaN  ...     NaN  NaN  All Sectors
318081          YEM           NaN          NaN  ...     NaN  NaN  All Sectors
318155          YEM           NaN          NaN  ...     NaN  NaN  All Sectors
318214          YEM           NaN          NaN  ...     NaN  NaN  All Sectors

[3701 rows x 17 columns]